name: Generate CloudFormation Script
run-name: Generating CloudFormation Script
on:
  push:
    paths:
      - remote-aws/cdk/** # only run on changes to cdk
jobs:
  synth-cdk:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: cdk synth
        uses: youyo/aws-cdk-github-actions@v2
        with:
            cdk_subcommand: 'synth'
            working_dir: 'remote-aws/cdk'
            cdk_stack: 'DashboardStack'
        env:
            # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_ACCESS_KEY_ID: "access_key"
            AWS_SECRET_ACCESS_KEY: "secret_access_key"
            AWS_DEFAULT_REGION: 'eu-west-1'
      - name: Report current directory
        run: pwd
      - name: Upload CloudFormation Template
        run: |
          cp remote-aws/cdk/cdk.out/*.template.json remote-aws
          # Configure Bot's information
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add remote-aws/*.template.json
          git commit -m "chore: generate CloudFormation template"
          git push
