name: Generate CloudFormation Scripts and Deploy
run-name: Generating and Deploying CloudFormation Scripts
on:
  push:
    paths:
      - remote-aws/cdk/** # only run on changes to cdk
env:
  AWS_REGION: 'eu-west-2'
jobs:
  synth-cdk:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Run cdk synth
        uses: youyo/aws-cdk-github-actions@v2
        with:
            cdk_subcommand: 'synth'
            working_dir: 'remote-aws/cdk'
            cdk_args: '-q'
        env:
            AWS_ACCESS_KEY_ID: "access_key"
            AWS_SECRET_ACCESS_KEY: "secret_access_key"
            AWS_DEFAULT_REGION: 'eu-west-2'
      - name: Copy and Cleanse CloudFormation Template of CDK
        run: |
          cp remote-aws/cdk/cdk.out/*.template.json remote-aws
          python3 build/strip_cdk.py
      - name: Commit CloudFormation Template if necessary
        run: |
          # Configure Bot's information
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # get git diff
          set +e
          git diff --exit-code remote-aws/*.template.json
          DIFFERENCE=$?
          echo git diff exit code = $DIFFERENCE
          if [ $DIFFERENCE -ne 0 ]
          then
            git add remote-aws/*.template.json
            git status
            git commit -m "chore: generate CloudFormation templates"
            git push
            echo "Changes committed"
          else
            echo "No changes since last run"
          fi
          set -e
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Copy Public CloudFormation Template
        run: aws s3 cp remote-aws/DashboardStack.template.json s3://${{ vars.codeBucket }}
      - name: Deploy Deployment CloudFormation Template
        run: >
          aws cloudformation deploy
          --template-file remote-aws/DeploymentStack.template.json
          --stack-name DashboardStack
          --parameter-overrides codeBucketName=${{ vars.codeBucket }}
      - name: Deploy Dashboard CloudFormation Template
        run: >
          aws cloudformation deploy
          --template-file remote-aws/DashboardStack.template.json
          --stack-name DashboardStack
          --parameter-overrides uniqueId=${{ secrets.UNIQUE_ID }}
          codeBucketName=${{ vars.codeBucket }}
      - name: Deploy Instructions CloudFormation Template
        run: >
          aws cloudformation deploy
          --template-file remote-aws/InstructionsStack.template.json
          --stack-name InstructionsStack
          --parameter-overrides publicUniqueId=${{ secrets.PUBLIC_UNIQUE_ID }}
          uniqueId=${{ secrets.UNIQUE_ID }}
        
